Q1_1:
    model_type: 'MLPa'
    init_type: 'normal'
    lr0: 0.02
    batch_size: 64
    num_epochs: 100
    weight_decay: 0
    batch_norm: false
    filename: 'Q1_1'
    fig_caption: 'no regularization'
Q1_2:
    model_type: 'MLPa'
    init_type: 'normal'
    lr0: 0.02
    batch_size: 64
    num_epochs: 100
    weight_decay: 2.5
    batch_norm: false
    filename: 'Q1_2'
    fig_caption: 'l2 regularization'
Q1_3:
    model_type: 'MLPb'
    init_type: 'normal'
    lr0: 0.02
    batch_size: 64
    num_epochs: 100
    weight_decay: 0
    batch_norm: false
    filename: Q1_3
    fig_caption: 'dropout, p=0.5'
Q1_4:
    model_type: 'MLPb'
    init_type: 'normal'
    lr0: 0.02
    batch_size: 64
    num_epochs: 100
    weight_decay: 0
    batch_norm: false
    filename: 'Q1_4'
    fig_caption: 'sample dropout mask, softmax and average'
Q1_5:
    model_type: 'MLPb'
    init_type: 'normal'
    lr0: 0.02
    batch_size: 64
    num_epochs: 100
    weight_decay: 0
    batch_norm: false
    filename: 'Q1_5'
    fig_caption: 'sample dropout mask, and average'
Q1_6:
    model_type: 'CNN'
    init_type: 'normal'
    lr0: 0.0001
    batch_size: 128
    num_epochs: 10
    weight_decay: 0.0005
    batch_norm: true
    filename: 'Q1_6'
    fig_caption: 'batch norm'
Q1_7:
    model_type: 'CNN'
    init_type: 'normal'
    lr0: 0.0001
    batch_size: 128
    num_epochs: 10
    weight_decay: 0.0005
    batch_norm: false
    filename: 'Q1_6'
    fig_caption: 'no batch norm'
Q2:
    num_epochs: 10
    image_size: 64
    train_size: 16000
    valid_size: 4000
    test_size: 4990
    batch_size_train: 25
    batch_size_valid: 50
    batch_size_test: 1
    lr0: 0.001
    momentum: 0.9
    data_set_path: 'datasets/PetImages'
    model_sample_interval: 10

