LSTM:
    model_type: 'LSTM'
    learning_rate: 0.001
    batch_size: 50
    num_epochs: 100
    momentum: 0.9
    filename: 'LSTM'
    interval: 100
    seq_len_min: 1
    seq_len_max: 20
    num_hidden: 100
    num_batches: 1000
    data_width: 8
LSTM_NTM:
    model_type: 'LSTM_NTM'
    learning_rate: 0.0001
    batch_size: 50
    num_epochs: 2000
    momentum: 0.9
    filename: 'LSTM_NTM'
    interval: 100
    seq_len_min: 1
    seq_len_max: 20
    num_hidden: 100
    num_batches: 1000
    data_width: 8
MLP_NTM:
    model_type: 'MLP_NTM'
    learning_rate: 0.001
    batch_size: 50
    num_epochs: 100
    momentum: 0.9
    filename: 'MLP_NTM'
    interval: 100
    seq_len_min: 1
    seq_len_max: 20
    num_hidden: 100
    num_batches: 1000
    data_width: 8
