LSTM:
    model_type: 'LSTM'
    learning_rate: 0.001
    batch_size: 1
    num_epochs: 100
    momentum: 0.9
    filename: 'lstm_checkpoint'
    interval: 100
    seq_len_min: 2
    seq_len_max: 2
    num_hidden: 100
    num_batches: 20000
    data_width: 8
LSTM_NTM:
    model_type: 'LSTM_NTM'
    learning_rate: 0.001
    batch_size: 1
    num_epochs: 100
    momentum: 0.9
    filename: 'lstm_ntm_checkpoint'
    interval: 100
    seq_len_min: 2
    seq_len_max: 2
    num_hidden: 100
    num_batches: 20000
    data_width: 8
MLP_NTM:
    model_type: 'MLP_NTM'
    learning_rate: 0.001
    batch_size: 1
    num_epochs: 100
    momentum: 0.9
    filename: 'mlp_ntm_checkpoint'
    interval: 100
    seq_len_min: 2
    seq_len_max: 2
    num_hidden: 100
    num_batches: 20000
    data_width: 8
